### ISSUE TITLE
sleep_api.h missing

### ISSUE THREAD

**Issue by drmpf** [lancaster-university/mbed-classic#1]
Compiling ble uart sample code 
Example micro:bit application - Animal Vegetable Mineral game
under netbeans/yotta gives
sleep_api.h missing include
checking the repository shows it is indeed missing

**Comment by jamesadevine** [comment]
@drmpf I presume that you are building from clones of the repositories from GitHub, and you are using yotta to compile?

**Comment by drmpf** [comment]
I have a detailed posting on [how I build here](http://www.forward.com.au/pfod/microbit/compileSetup.html) 
The initial pull of the repositories is done via yotta as is the initial compile, then subsequent compiles via netbeans (no new source files added)

**Comment by jamesadevine** [comment]
@drmpf It must be a netbeans-ism (i think), sleep_api.h is here: https://github.com/lancaster-university/mbed-classic/blob/master/hal/sleep_api.h

**Comment by drmpf** [comment]
Ok found it and so does the build under Netbeans, but just tried a completely clean project yotta init etc with the main.cpp and Netbeans still complains about a missing sleep_api.h.
Added 
sleep(); 
and all compiles, but being C/C++ that is not saying much.
tried sleep(10); and got a compile error that referenced the /hal/sleep.api.h declaration so Netbeans compile if actually find it.  
It seems just the code include processing is missing it and also yotta_cfg_mappings.h
So closing these two issues.
